### ISSUE TITLE
Incorrect proj.db version on heroku

### ISSUE THREAD

**Issue by JonRowe** [mapnik/node-mapnik#1011]
Hello! I'm trying to use this library (and its bundled `so`) on Heroku, I've had to tell Heroku to use the bundled `.so` by setting LD_LIBRARY_PATH but now I'm getting this error:

```
/app/node_modules/@mapnik/mapnik/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 3 whereas a number >= 4 is expected. It comes from another PROJ installation.
```

I don't think Heroku dyno's have there own version of proj so is the bundled one incompatible with the library file?

**Comment by artemp** [comment]
@JonRowe - Could you provide steps to replicate this issue? I'm not familiar with Heroku, but if you're using
`npm install @mapnik/mapnik`  you should get a working `node-mapnik` without ammending/setting `LD_LIBRARY_PATH`.
It sounds like you have multiple versions of libraries which create conflict at runtime.

**Comment by JaylanChen** [comment]
When I upgraded v4.6.7, the same error occurred.
```
pj_obj_create: /app/node_modules/@mapnik/mapnik/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 3 whereas a number >= 4 is expected. It comes from another PROJ installation.

proj_create_operation_factory_context: /app/node_modules/@mapnik/mapnik/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 3 whereas a number >= 4 is expected. It comes from another PROJ installation.
```

**Comment by artemp** [comment]
@JaylanChen - which are post platform + arch are you using?

**Comment by artemp** [comment]
@JonRowe @JaylanChen - I'll address this issue asap in https://github.com/mapnik/node-mapnik/milestone/45

**Comment by artemp** [comment]
@JonRowe @JaylanChen 

[v4.6.8](https://github.com/mapnik/node-mapnik/tree/v4.6.8) should fix this issue 

`@mapnik:registry=https://npm.pkg.github.com/` -  https://www.npmjs.com/package/@mapnik/mapnik/v/4.6.8 
`@mapnik:registry=https://registry.npmjs.org/` - https://github.com/mapnik/node-mapnik/pkgs/npm/mapnik/359408729

**Comment by JaylanChen** [comment]
`linux-x64`   `v4.6.8 `
No such error has occurred.

**Comment by JonRowe** [comment]
I still get this error when overriding `LD_LIBRARY_PATH`, I'm trying to install mapnik 4 into the heroku container to see if that solves it (theres not normally anymapnik installed) (I'm upgrading this from an older version that worked self contained)

**Comment by JonRowe** [comment]
I've rechecked this seeing as its marked as completed, I still have to override the LD_LIBRARY_PATH with:
```
 heroku config:set LD_LIBRARY_PATH='/app/node_modules/@mapnik/core-linux-x64/lib/:$LD_LIBRARY_PATH'
```
But the most recent version does resolve the proj.db issue thank you

**Comment by JonRowe** [comment]
That might not be enough FWIW, buildpacks operate in two stages which are isolated more so than dockers layers
