### ISSUE TITLE
something broken with v4.5.0 regarding scale_factor / zoom level ?

### ISSUE THREAD

**Issue by cquest** [mapnik/node-mapnik#952]
I've upgraded node-mapnik on my kosmtik install to v4.5.0 and the scale_factor or zoom in cartocss seems completely broken, rendering all zoom levels like the highest one.

Downgrading to v4.4.0 solve the issue immediately.
I'm running on node v12 (current LTS)

**Comment by artemp** [comment]
@cquest - thanks for reporting.

**Comment by artemp** [comment]
@cquest - I found the issue: default `scale_denominator` value should be initialised to 0.0 in order to trigger

```c++
 if (scale_denom <= 0.0)
 {
     scale_denom = mapnik::scale_denominator(m_req.scale(), map_proj.is_geographic());
 }
```
  could you try a1a08d0 and see if everything is working as expected? cheers

**Comment by cquest** [comment]
I've installed node-mapnik with (not sure about it, I'm not used to this):

npm i mapnik/node-mapnik#a1a08d077fff7474f05fe04fd7f1af4eb49c3c07

Re-ran kosmtik... and still the same problem

npm i mapnik@4.4.0 -> ok again

**Comment by artemp** [comment]
@cquest ok, I don't thinks you can just pull new binary package like that, thanks for trying!  I'm pretty sure this issue is fixed in a1a08d0 but I found couple more issues I'll need to fix before publishing `4.5.1`

**Comment by cquest** [comment]
I'll check 4.5.1 once it's available.

Thanks for your lightning fast feedback !

**Comment by springmeyer** [comment]
The v4.5.1 release is available now and should fix this. Please re-open if you find it did not and please create new issues for other other problems you encounter. Thanks @cquest!

**Comment by cquest** [comment]
I've just tested with 4.5.1 (npm i mapnik@4.5.1) and the problem is still there...

reverted with npm i mapnik@4.4.0 and all is ok.

It does not seem fixed.

**Comment by artemp** [comment]
@cquest - ok, must be something else here. Could you provide more info e.g carto css, anything else relevant to replicate this issue, please.

**Comment by springmeyer** [comment]
@artemp I see that there is still one `scale_denom` defaulting to 1. Perhaps that is the problem?

```bash
$ grep 'double scale_denominator =' src -r
src/mapnik_vector_tile_composite.cpp:    double scale_denominator = 0.0;
src/mapnik_vector_tile_composite.cpp:    double scale_denominator = 0.0;
src/mapnik_map_render.cpp:        double scale_denominator = 1.0;
src/mapnik_map_render.cpp:    double scale_denominator = 0.0;
src/mapnik_map_render.cpp:    double scale_denominator = 0.0;
src/mapnik_map_render.cpp:    double scale_denominator = 0.0;
src/mapnik_vector_tile_render.cpp:    double scale_denominator = 0.0;
```

**Comment by artemp** [comment]
@springmeyer that could be it, indeed.

**Comment by ticktricktrack** [comment]
We're having a similar issue. `maximumExtent` https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_map.cpp#L235-L250 seems to only expect `floats`, no longer `strings`. 

But even if we convert them beforehand we still see similar issues.

**Comment by artemp** [comment]
@ticktricktrack maximumExtent (settter) now expect JS array of exactly four floating point numbers. I don't think accepting and converting strings internally to floats is a good design. 
@ticktricktrack @cquest - I just published `mapnik@4.5.2`. Let me know, cheers

**Comment by cquest** [comment]
It seems ok with v4.5.2 :)

**Comment by artemp** [comment]
ok, great, closing, thanks.
